apiVersion: v2
appVersion: "1.0"
description: A Helm chart for spring-boot-template App
name: rpe-spring-boot-template
home: https://github.com/hmcts/spring-boot-template
version: 0.0.2
maintainers:
  - name: HMCTS rpe team
dependencies:
  - name: java
    version: 4.0.11
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
